### ISSUE TITLE
df issues batch 3

### ISSUE THREAD

**Issue by obernardovieira** [impactMarket/app#241]
# Hugo

- [x] * In community page, there are 2 email icons. It should be an email icon and a phone icon
- [x] * In Notifications, the link of each notification should be directly “connected” to the notification.
- [x] * In contribute, the message after approving/contributing cUSD is only “success”. It should be capitalized or even change the message.
- [x] * When there’s no wallet connected the logo link does nothing

# Paulo Soares

- [x] * After log in the user should be redirected to his dashboard

# Paulo Sousa

- [x] * In community details, promoter social icons not found and components style is broken
- [x] * On mobile communities page, we have a outer scroll and 2 connect wallet buttons - see "navigation side - mobile" on design to fix

# João

- [x] * Filter by country showing countries that dont have accepted communities (to solve use "status=valid" /communities/count?groupBy=country&status=valid)

# Bernardo

- [x] * When the user has no communities, values should default to zero
- [x] * Communities with zero beneficiaries should show the card anyways with zero there (on community page)
- [x] * increment interval on proposals description is wrong. See proposal #26. Should be 5 minutes. It's missing the blocks number division, needs to be divided by 12, like on community page

**Comment by hugomarquesdev** [comment]
@obernardovieira 

`* increment interval on proposals description is wrong. See proposal https://github.com/impactMarket/app/pull/26. Should be 5 minutes. It's missing the blocks number division, needs to be divided by 12, like on community page`:

- the proposals data is coming from the utils (useImpactMarketCouncil). In frontend, we receive the entire description as a value with "description" key. I don't think I can change that in frontend. Can you confirm if this should be a backend fix?

![Image](https://user-images.githubusercontent.com/62065869/183630150-7536c8a1-f8fa-4c22-ab10-29e336527b6b.png)

**Comment by obernardovieira** [comment]
It was fixed [here](https://github.com/impactMarket/app/pull/247/files#diff-16716e3574b00b47970ec78f489f810cd38f2b8ed1c3689c9b26e135523bfad1R73). See PR comments for reference.
