### ISSUE TITLE
Ambassadors don't see the edit button where they are ambassadors

### ISSUE THREAD

**Issue by obernardovieira** [impactMarket/app#402]
(this is from council, ambassadors don't have it)
account example: Ambassador 3 in https://app-alfajores.impactmarket.com/communities/7216
<img width="614" alt="image" src="https://user-images.githubusercontent.com/19441097/218161055-7f32a494-0d27-427d-b624-7d8b61296b00.png">

**Comment by hugomarquesdev** [comment]
this happens because, _only in some communities_, the **community endpoint** returns the `ambassadorAddress` as `null`.  I fixed it by getting the ambassador's address from the contract.
Anyway, shouldn't the `ambassadorAddress` from the community endpoint always return the ambassador's address?
