### ISSUE TITLE
dApp: "Back" button not working in some pages

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/app#425]
When in the dApp, there are pages that the "Back" button didn't work and, when going back using the phone's "back" function, I'm leaving the dApp instead of going back to the previous page. This should be clearer to facilitate the navigation inside the different pages on the dApp

- reported by Susanne using a Community Manager Account

https://user-images.githubusercontent.com/127307303/225596130-3ad379f7-e470-4a71-bd7a-042bab4aed4a.mp4

https://user-images.githubusercontent.com/127307303/225596201-3e6a39ac-6ba3-4ece-8faf-b783e1acd72a.mp4

m

**Comment by hugomarquesdev** [comment]
@Marianavpt 
the "⬅️ 🏠 ➡️" icons are from the wallet side and not from the dapp (first video);
about the "⬅️ Voltar" button (in the second video), I can't replicate on my side. I've tried with testnet and mainnet (inside the wallet) and its working fine. 🤔

**Comment by Marianavpt** [comment]
Should I ask Susanne to try again?

**Comment by hugomarquesdev** [comment]
@Marianavpt yes

**Comment by Marianavpt** [comment]
@hugomarquesdev just tested now and I am experiencing exactly the same issue as Susanne reported, sending you a video right away

**Comment by hugomarquesdev** [comment]
@Marianavpt oh wait! i think it only happens in "My Community"   
can you try another page? like another community in communities?

**Comment by hugomarquesdev** [comment]
@Marianavpt i can only replicate the issue when I go to My Community. In both of those pages (Beneficiaries and Learn&Earn) is working fine for me...
I'll try to fix it today.

**Comment by hugomarquesdev** [comment]
@obernardovieira yup...
@Marianavpt can you test it again? I still cant replicate the issue (webapp side is only the Back button), i can only replicate it on My Community.

**Comment by Marianavpt** [comment]
@hugomarquesdev I am not able to test on the dApp inside Libera, since I am not able to Connect my Wallet, but I can test on the    web app and share a video ok?

**Comment by Marianavpt** [comment]
https://user-images.githubusercontent.com/127307303/233355912-25cb093e-3d31-428d-ac85-beff5522c847.mp4

**Comment by Marianavpt** [comment]
Is this working?

**Comment by hugomarquesdev** [comment]
@Marianavpt it's fixed in this PR:
https://github.com/impactMarket/app/pull/463
