### ISSUE TITLE
L&E: the success message is not showing up when I finish a lesson. iOS(safari) by Afonso

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/app#432]
L&E: the success message is not showing up when I finish a lesson. iOS(safari) 

![IMG_0606](https://user-images.githubusercontent.com/127307303/226991481-6be6aeaf-3b48-4abd-bcd2-ffc2ddecd171.png)

**Comment by obernardovieira** [comment]
Missing text maybe.
@PauloSousapt @hugomarquesdev

**Comment by Marianavpt** [comment]
Any news on this issue? I've checked now and I have the same issue:

![File (8)](https://user-images.githubusercontent.com/127307303/228265733-dcd8df47-901f-4bb4-80b5-24442636a3e3.jpg)

**Comment by PauloSousapt** [comment]
Yes @Marianavpt, the problem is identified and still not fixed, all the effort at the moment is on completing the first phase of the microcredit this week. Only after i'll have a window to fix this.

**Comment by PauloSousapt** [comment]
@Marianavpt The fix for this issue was deployed to production, this error should be gone now.

**Comment by Marianavpt** [comment]
how are on this @PauloSousapt ? :)

**Comment by PauloSousapt** [comment]
I've answered it in the previous comment 🙂. The fix it's deployed, should be fixed now.

**Comment by Marianavpt** [comment]
great, thanks!

**Comment by Marianavpt** [comment]
Waitinf for final validation from Paulo and translations on the Prismic side

**Comment by Marianavpt** [comment]
It's working, only missing translations on Prismic side now.![IMG_F253BD71518D-1](https://user-images.githubusercontent.com/127307303/233433199-52a62a84-f368-4d1d-a53d-54a0330874ee.jpeg)
