### ISSUE TITLE
[beneficiary view] amount claimed doesn't update

### ISSUE THREAD

**Issue by obernardovieira** [impactMarket/app#436]
I've refreshed the page, but still didn't update.

![image](https://user-images.githubusercontent.com/19441097/230021168-f5572721-d5ce-47e0-8c2d-edb7fc85f132.png)

**Comment by obernardovieira** [comment]
It seems to round to numbers like 1,2,3, without decimals. Might be an issue on utils.

**Comment by obernardovieira** [comment]
> It seems to round to numbers like 1,2,3, without decimals. Might be an issue on utils.

It is. In fact, there's a few issues here https://github.com/impactMarket/utils/blob/main/src/useBeneficiary.tsx#L94
All this parseNumber should actually be parseFloat

**Comment by hugomarquesdev** [comment]
@obernardovieira I'm trying to solve this but, even though the transaction is successful, the data returned from the `useBeneficiary` hook won't update even if I refresh the page.
In front-end we're just printing the data that comes from that hook directly.
