### ISSUE TITLE
dApp: Suspicious Activity Page is not working

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/app#503]
When going into “Ambassador dashboard” >  “my community” > “krisan Refugee camp” > “ Suspicious activity” > “View all”, I receive the 404 error message - reported by Rosaline on Android and Jessica on iOS
 

![image](https://github.com/impactMarket/support-issues/assets/127307303/6ad41f57-7c29-40cd-a2f5-862014cb9242)

**Comment by obernardovieira** [comment]
@hugomarquesdev remove the "Reported Suspicious Activity" please. We are not doing anything about it serverside. It's not working for now.
