### ISSUE TITLE
application history under user profile has wrong details

### ISSUE THREAD

**Issue by obernardovieira** [impactMarket/app#629]
![image](https://github.com/impactMarket/app/assets/19441097/1fa49b33-96f6-4713-90a8-80a7bcc82d36)

It's pending, but there is a date to "accepted". No "applied".

**Comment by hugomarquesdev** [comment]
> It's pending, but there is a date to "accepted". No "applied".

@obernardovieira i've checked the users from testnet and everything seems fine. the status is being called exactly with the same method both on the user's page and the loan manager page, so, the status is correct.
if there's data on the `decision` and `accepted` it's coming from backend 🤔

**Comment by obernardovieira** [comment]
correct, this was backend https://github.com/impactMarket/backend/pull/1027
